// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table table_from_ES1 (ArrayIndex_temperature_readings:long, ArrayValue_temperature_readings:dynamic, country:string, city:string, timestamp:string, event_id:string) 
.create-merge table Hopping (COUNT_All:long, Window_End_Time:datetime) 
.create-merge table Tumbling (COUNT_All:long, Window_End_Time:datetime) 
.create-merge table Snapshot (COUNT_All:long, Window_End_Time:datetime) 
.create-merge table Session (COUNT_All:long, Window_End_Time:datetime) 
.create-merge table raw (timestamp:string, message:string, message_id:string) 
.create-merge table Sliding (COUNT_All:long, Window_End_Time:datetime) 
